#!/usr/bin/env python3

import json
import keyword
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "WorthItApp" / "Resources" / "Localizable.xcstrings"
OUTPUT_PATH = ROOT / "WorthItApp" / "Core" / "Localization" / "I18nKey.generated.swift"


SWIFT_KEYWORDS = {
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate",
    "func", "import", "init", "inout", "internal", "let", "open",
    "operator", "private", "precedencegroup", "protocol", "public",
    "rethrows", "static", "struct", "subscript", "typealias", "var",
    "break", "case", "catch", "continue", "default", "defer", "do",
    "else", "fallthrough", "for", "guard", "if", "in", "repeat",
    "return", "throw", "switch", "where", "while", "Any", "as", "await",
    "catch", "false", "is", "nil", "self", "Self", "super", "throws",
    "true", "try",
}


class Node:
    def __init__(self):
        self.children = {}
        self.key = None


def split_words(token: str) -> list[str]:
    pieces = re.split(r"[^A-Za-z0-9]+", token)
    words: list[str] = []
    for piece in pieces:
        if not piece:
            continue
        # Preserve existing camelCase reasonably well while still handling
        # kebab/snake/raw catalog segments.
        words.extend(re.findall(r"[A-Z]+(?=[A-Z][a-z]|$)|[A-Z]?[a-z]+|[0-9]+", piece))
    return words or ["key"]


def lower_camel(token: str) -> str:
    words = split_words(token)
    first = words[0].lower()
    rest = "".join(word[:1].upper() + word[1:] for word in words[1:])
    name = first + rest
    if name[:1].isdigit():
        name = "_" + name
    if name in SWIFT_KEYWORDS or keyword.iskeyword(name):
        name = f"`{name}`"
    return name


def upper_camel(token: str) -> str:
    words = split_words(token)
    name = "".join(word[:1].upper() + word[1:] for word in words)
    if name[:1].isdigit():
        name = "_" + name
    if name in SWIFT_KEYWORDS:
        name += "Keys"
    return name


def swift_string(value: str) -> str:
    return json.dumps(value)


def insert(root: Node, key: str) -> None:
    parts = key.split(".")
    node = root
    for part in parts:
        node = node.children.setdefault(part, Node())
    node.key = key


def collect_semantic_keys(strings: dict) -> tuple[list[str], list[str]]:
    semantic: list[str] = []
    skipped: list[str] = []
    for key in sorted(strings):
        parts = key.split(".")
        if len(parts) >= 2 and all(re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", part) for part in parts):
            semantic.append(key)
        else:
            skipped.append(key)
    return semantic, skipped


def validate_tree(node: Node, path: list[str]) -> None:
    if node.key is not None and node.children:
        joined = ".".join(path)
        raise SystemExit(
            f"i18n key conflict: '{joined}' is both a translation key and a namespace. "
            "Rename one side, for example use '.title' or '.label' for the leaf key."
        )
    for part, child in node.children.items():
        validate_tree(child, path + [part])


def emit_struct(name: str, node: Node, depth: int, out: list[str]) -> None:
    indent = "    " * depth
    child_items = sorted(node.children.items())

    out.append(f"{indent}struct {name} {{")
    if not child_items:
        out.append(f"{indent}}}")
        return

    for part, child in child_items:
        prop_name = lower_camel(part)
        if child.children:
            type_name = f"{upper_camel(part)}Keys"
            out.append(f"{indent}    let {prop_name} = {type_name}()")
        else:
            out.append(f"{indent}    let {prop_name} = I18nKey({swift_string(child.key)})")

    nested = [(part, child) for part, child in child_items if child.children]
    for part, child in nested:
        out.append("")
        emit_struct(f"{upper_camel(part)}Keys", child, depth + 1, out)

    out.append(f"{indent}}}")


def main() -> None:
    catalog = json.loads(CATALOG_PATH.read_text())
    semantic_keys, skipped_keys = collect_semantic_keys(catalog.get("strings", {}))

    root = Node()
    for key in semantic_keys:
        insert(root, key)
    validate_tree(root, [])

    lines: list[str] = [
        "// Generated by scripts/generate_i18n_keys.py. Do not edit by hand.",
        "// Source of truth: WorthItApp/Resources/Localizable.xcstrings",
        "",
        "import Foundation",
        "",
        "struct I18nKey: Hashable {",
        "    let value: String",
        "",
        "    fileprivate init(_ value: String) {",
        "        self.value = value",
        "    }",
        "}",
        "",
        "extension I18nKey {",
    ]

    for part, child in sorted(root.children.items()):
        lines.append(f"    static let {lower_camel(part)} = {upper_camel(part)}Keys()")

    lines.append("}")

    for part, child in sorted(root.children.items()):
        lines.append("")
        emit_struct(f"{upper_camel(part)}Keys", child, 0, lines)

    lines.append("")
    lines.append(f"// Skipped {len(skipped_keys)} legacy non-semantic catalog keys.")

    OUTPUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} from {len(semantic_keys)} semantic keys")
    if skipped_keys:
        print(f"Skipped {len(skipped_keys)} legacy non-semantic keys")


if __name__ == "__main__":
    main()
