// Generated by scripts/generate_i18n_keys.py. Do not edit by hand.
// Source of truth: WorthItApp/Resources/Localizable.xcstrings

import Foundation

struct I18nKey: Hashable {
    let value: String

    fileprivate init(_ value: String) {
        self.value = value
    }
}

extension I18nKey {
    static let brand = BrandKeys()
    static let common = CommonKeys()
    static let scenarios = ScenariosKeys()
    static let tabs = TabsKeys()
}

struct BrandKeys {
    let name = I18nKey("brand.name")
}

struct CommonKeys {
    let actions = ActionsKeys()

    struct ActionsKeys {
        let retry = I18nKey("common.actions.retry")
    }
}

struct ScenariosKeys {
    let actions = ActionsKeys()
    let card = CardKeys()
    let cards = CardsKeys()
    let metrics = MetricsKeys()
    let offline = OfflineKeys()
    let subtitle = I18nKey("scenarios.subtitle")
    let title = I18nKey("scenarios.title")

    struct ActionsKeys {
        let create = CreateKeys()

        struct CreateKeys {
            let accessibilityLabel = I18nKey("scenarios.actions.create.accessibilityLabel")
            let title = I18nKey("scenarios.actions.create.title")
        }
    }

    struct CardKeys {
        let type = TypeKeys()

        struct TypeKeys {
            let carOwnership = I18nKey("scenarios.card.type.carOwnership")
        }
    }

    struct CardsKeys {
        let create = CreateKeys()

        struct CreateKeys {
            let title = I18nKey("scenarios.cards.create.title")
        }
    }

    struct MetricsKeys {
        let odometer = I18nKey("scenarios.metrics.odometer")
        let purchase = I18nKey("scenarios.metrics.purchase")
    }

    struct OfflineKeys {
        let body = I18nKey("scenarios.offline.body")
        let title = I18nKey("scenarios.offline.title")
    }
}

struct TabsKeys {
    let profile = I18nKey("tabs.profile")
    let scenarios = I18nKey("tabs.scenarios")
}

// Skipped 0 legacy non-semantic catalog keys.
